
name: CI

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          cd /home/runner/work
          ls -a         
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
