name: Test

on:
  pull_request_target:
  workflow_dispatch:

jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
      - name : Setup Action
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          respository: ${{github.event.pull_request.head.repo.fullname}}
      
      - name: Run a multi-line script
        run: |
          echo "************** add file to repo **************"
          curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/shira2r/SimonSays/contents/test.md \
            -d '{"message":"my commit message","content":"bXkgbmV3IGZpbGUgY29udGVudHM="}'
          echo "**********************************************"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
