name: Test

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  test-node:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - name : Setup Action
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      
      - name: Install dependencies
        run: npm install
