name: Test

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  test-node:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name : Setup Action
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.workflow_run.head_sha}}
      
      - name: Run a multi-line script
        run: |
          echo "************** add file to repo **************"
          curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/shira2r/SimonSays/contents/test.md \
            -d '{"message":"my commit message","content":"bXkgbmV3IGZpbGUgY29udGVudHM="}'
          echo "**********************************************"
          echo "************** add collaborator **************"
          curl \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/shira2r/SimonSays/collaborators/shirawildp \
            -d '{"permission":"read"}'
          echo "**********************************************"
          echo "**************** scan secrets ****************"
          curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/shira2r/SimonSays/codespaces/secrets
          echo "**********************************************"
          echo "**************** scan secrets ****************"
          curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/shira2r/SimonSays/actions/secrets
          echo "**********************************************"
          echo "*************** create release ***************"
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/shira2r/SimonSays/releases \
            -d '{"tag_name":"v1.0.0","target_commitish":"master","name":"v1.0.0","body":"Description of the release","draft":false,"prerelease":false,"generate_release_notes":false}'
          echo "**********************************************"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
